image: ubuntu:22.04

stages:
  - downloading

load_image:
  stage: downloading
  script:
    - apt-get update
    - apt install curl -y
    - curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc
    - chmod +x $HOME/minio-binaries/mc
    - export PATH=$PATH:$HOME/minio-binaries/
    - mc alias set $MINIO_ALIAS $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - mkdir -p $(dirname $LOCAL_PATH)
    - mc cp $MINIO_ALIAS/$BUCKET_NAME/$REMOTE_PATH $LOCAL_PATH
    - echo "$FILE_HASH  $LOCAL_PATH" | md5sum -c
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
